apiVersion: apps/v1
kind: Deployment
metadata:
  name: spreadacross
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: spreadacross
  template:
    metadata:
      labels:
        app: spreadacross
    spec: 
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: spreadacross
      containers:
        - name: spreadacross-container
          image: nginx
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: spreadacross-service
# spec:
#   selector:
#     app: spreadacross
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80
#   type: LoadBalancer  